# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modul_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modul_modulpage(object):
    def setupUi(self, Modul_modulpage):
        Modul_modulpage.setObjectName("Modul_modulpage")
        Modul_modulpage.resize(791, 509)
        Modul_modulpage.setStyleSheet("background: #012A3B;\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(Modul_modulpage)
        self.centralwidget.setObjectName("centralwidget")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(630, 0, 91, 31))
        self.back_button.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.nama_label = QtWidgets.QLabel(self.centralwidget)
        self.nama_label.setGeometry(QtCore.QRect(10, 0, 161, 21))
        self.nama_label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.nama_label.setObjectName("nama_label")
        self.npm_label = QtWidgets.QLabel(self.centralwidget)
        self.npm_label.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.npm_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.npm_label.setObjectName("npm_label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 471, 181))
        self.groupBox.setStyleSheet("background: #427697;")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 41, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 281, 21))
        self.label_2.setObjectName("label_2")
        self.num = QtWidgets.QTextEdit(self.groupBox)
        self.num.setGeometry(QtCore.QRect(170, 20, 51, 31))
        self.num.setStyleSheet("background: white;\n"
"color: black;")
        self.num.setObjectName("num")
        self.denum = QtWidgets.QTextEdit(self.groupBox)
        self.denum.setGeometry(QtCore.QRect(40, 60, 41, 31))
        self.denum.setStyleSheet("background: white;\n"
"color: black;")
        self.denum.setObjectName("denum")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(90, 60, 31, 21))
        self.label_3.setObjectName("label_3")
        self.denum_2 = QtWidgets.QTextEdit(self.groupBox)
        self.denum_2.setGeometry(QtCore.QRect(130, 60, 41, 31))
        self.denum_2.setStyleSheet("background: white;\n"
"color: black;")
        self.denum_2.setObjectName("denum_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(190, 60, 31, 21))
        self.label_4.setObjectName("label_4")
        self.denum_3 = QtWidgets.QTextEdit(self.groupBox)
        self.denum_3.setGeometry(QtCore.QRect(230, 60, 41, 31))
        self.denum_3.setStyleSheet("background: white;\n"
"color: black;")
        self.denum_3.setObjectName("denum_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(280, 60, 31, 21))
        self.label_5.setObjectName("label_5")
        self.denum_4 = QtWidgets.QTextEdit(self.groupBox)
        self.denum_4.setGeometry(QtCore.QRect(300, 60, 41, 31))
        self.denum_4.setStyleSheet("background: white;\n"
"color: black;")
        self.denum_4.setObjectName("denum_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 41, 41))
        self.label_6.setObjectName("label_6")
        self.kv = QtWidgets.QTextEdit(self.groupBox)
        self.kv.setGeometry(QtCore.QRect(50, 100, 61, 31))
        self.kv.setStyleSheet("background: white;\n"
"color: black;")
        self.kv.setObjectName("kv")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 51, 41))
        self.label_7.setStyleSheet("background: transparent;")
        self.label_7.setObjectName("label_7")
        self.OS = QtWidgets.QTextEdit(self.groupBox)
        self.OS.setGeometry(QtCore.QRect(80, 140, 61, 31))
        self.OS.setStyleSheet("background: white;\n"
"color: black;")
        self.OS.setObjectName("OS")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(150, 130, 21, 41))
        self.label_8.setStyleSheet("background: transparent;")
        self.label_8.setObjectName("label_8")
        self.generate = QtWidgets.QPushButton(self.groupBox)
        self.generate.setGeometry(QtCore.QRect(350, 30, 101, 31))
        self.generate.setStyleSheet("background: #EDEEE9;\n"
"color: #012A3B;")
        self.generate.setObjectName("generate")
        self.bode = QtWidgets.QPushButton(self.groupBox)
        self.bode.setGeometry(QtCore.QRect(370, 130, 101, 31))
        self.bode.setStyleSheet("background: #EDEEE9;\n"
"color: #012A3B;")
        self.bode.setObjectName("bode")
        self.lag = QtWidgets.QRadioButton(self.groupBox)
        self.lag.setGeometry(QtCore.QRect(200, 100, 181, 31))
        self.lag.setObjectName("lag")
        self.lead = QtWidgets.QRadioButton(self.groupBox)
        self.lead.setGeometry(QtCore.QRect(200, 140, 171, 31))
        self.lead.setStyleSheet("background: transparent;")
        self.lead.setObjectName("lead")
        self.damping = QtWidgets.QLabel(self.centralwidget)
        self.damping.setGeometry(QtCore.QRect(10, 230, 111, 31))
        self.damping.setObjectName("damping")
        self.phasa = QtWidgets.QLabel(self.centralwidget)
        self.phasa.setGeometry(QtCore.QRect(160, 230, 141, 31))
        self.phasa.setObjectName("phasa")
        self.plotresponse = plotresponse(self.centralwidget)
        self.plotresponse.setGeometry(QtCore.QRect(10, 270, 771, 271))
        self.plotresponse.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.plotresponse.setStyleSheet("background: #EE414C;")
        self.plotresponse.setObjectName("plotresponse")
        self.phasa_max = QtWidgets.QLabel(self.centralwidget)
        self.phasa_max.setGeometry(QtCore.QRect(340, 230, 131, 31))
        self.phasa_max.setObjectName("phasa_max")
        self.besaran = QtWidgets.QLabel(self.centralwidget)
        self.besaran.setGeometry(QtCore.QRect(500, 60, 191, 31))
        self.besaran.setObjectName("besaran")
        self.frekuensimax = QtWidgets.QLabel(self.centralwidget)
        self.frekuensimax.setGeometry(QtCore.QRect(500, 100, 211, 31))
        self.frekuensimax.setObjectName("frekuensimax")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(500, 150, 51, 51))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(580, 160, 151, 31))
        self.label_13.setObjectName("label_13")
        self.num_compe = QtWidgets.QLabel(self.centralwidget)
        self.num_compe.setGeometry(QtCore.QRect(570, 140, 181, 31))
        self.num_compe.setStyleSheet("background: transparent;")
        self.num_compe.setText("")
        self.num_compe.setAlignment(QtCore.Qt.AlignCenter)
        self.num_compe.setObjectName("num_compe")
        self.denum_compe = QtWidgets.QLabel(self.centralwidget)
        self.denum_compe.setGeometry(QtCore.QRect(570, 190, 171, 31))
        self.denum_compe.setStyleSheet("background: transparent;")
        self.denum_compe.setText("")
        self.denum_compe.setAlignment(QtCore.Qt.AlignCenter)
        self.denum_compe.setObjectName("denum_compe")
        self.bode_compe = QtWidgets.QPushButton(self.centralwidget)
        self.bode_compe.setGeometry(QtCore.QRect(660, 230, 121, 31))
        self.bode_compe.setStyleSheet("background: #EDEEE9;\n"
"color: #012A3B;")
        self.bode_compe.setObjectName("bode_compe")
        self.graph = QtWidgets.QPushButton(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(510, 230, 111, 31))
        self.graph.setStyleSheet("background: #EDEEE9;\n"
"color: #012A3B;")
        self.graph.setObjectName("graph")
        Modul_modulpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Modul_modulpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 18))
        self.menubar.setObjectName("menubar")
        Modul_modulpage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Modul_modulpage)
        self.statusbar.setObjectName("statusbar")
        Modul_modulpage.setStatusBar(self.statusbar)

        self.retranslateUi(Modul_modulpage)
        QtCore.QMetaObject.connectSlotsByName(Modul_modulpage)

    def retranslateUi(self, Modul_modulpage):
        _translate = QtCore.QCoreApplication.translate
        Modul_modulpage.setWindowTitle(_translate("Modul_modulpage", "MainWindow"))
        self.back_button.setText(_translate("Modul_modulpage", "Menu Awal"))
        self.nama_label.setText(_translate("Modul_modulpage", "Nama"))
        self.npm_label.setText(_translate("Modul_modulpage", "NPM"))
        self.groupBox.setTitle(_translate("Modul_modulpage", "Masukkan TF Sistem yang didapat!"))
        self.label.setText(_translate("Modul_modulpage", "T(s) ="))
        self.label_2.setText(_translate("Modul_modulpage", "_________________________________________________________________"))
        self.num.setHtml(_translate("Modul_modulpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">180</p></body></html>"))
        self.denum.setHtml(_translate("Modul_modulpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.label_3.setText(_translate("Modul_modulpage", "s^3 +"))
        self.denum_2.setHtml(_translate("Modul_modulpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">25</p></body></html>"))
        self.label_4.setText(_translate("Modul_modulpage", "s^2 +"))
        self.denum_3.setHtml(_translate("Modul_modulpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">150</p></body></html>"))
        self.label_5.setText(_translate("Modul_modulpage", "s +"))
        self.denum_4.setHtml(_translate("Modul_modulpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_6.setText(_translate("Modul_modulpage", "Kv = "))
        self.kv.setHtml(_translate("Modul_modulpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">8</p></body></html>"))
        self.label_7.setText(_translate("Modul_modulpage", "%OS  = "))
        self.OS.setHtml(_translate("Modul_modulpage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">8</p></body></html>"))
        self.label_8.setText(_translate("Modul_modulpage", "%"))
        self.generate.setText(_translate("Modul_modulpage", "Generate"))
        self.bode.setText(_translate("Modul_modulpage", "Bode Plot"))
        self.lag.setText(_translate("Modul_modulpage", "Lag Compensator"))
        self.lead.setText(_translate("Modul_modulpage", "Lead Compensator"))
        self.damping.setText(_translate("Modul_modulpage", "ζ = "))
        self.phasa.setText(_translate("Modul_modulpage", "ϕmnew = "))
        self.phasa_max.setText(_translate("Modul_modulpage", "ϕmax = "))
        self.besaran.setText(_translate("Modul_modulpage", "Mmax = "))
        self.frekuensimax.setText(_translate("Modul_modulpage", "ωmax = "))
        self.label_12.setText(_translate("Modul_modulpage", "G(s) ="))
        self.label_13.setText(_translate("Modul_modulpage", "__________________________________"))
        self.bode_compe.setText(_translate("Modul_modulpage", "Bode"))
        self.graph.setText(_translate("Modul_modulpage", "Graph"))
from plotresponse import plotresponse


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Modul_modulpage = QtWidgets.QMainWindow()
    ui = Ui_Modul_modulpage()
    ui.setupUi(Modul_modulpage)
    Modul_modulpage.show()
    sys.exit(app.exec_())
