# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Modul_5.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Modul_modulpage(object):
    def setupUi(self, Modul_modulpage):
        Modul_modulpage.setObjectName("Modul_modulpage")
        Modul_modulpage.resize(631, 453)
        Modul_modulpage.setStyleSheet("background: #012A3B;\n"
"color: white;")
        self.centralwidget = QtWidgets.QWidget(Modul_modulpage)
        self.centralwidget.setObjectName("centralwidget")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(530, 30, 91, 31))
        self.back_button.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}")
        self.back_button.setObjectName("back_button")
        self.nama_label = QtWidgets.QLabel(self.centralwidget)
        self.nama_label.setGeometry(QtCore.QRect(10, 0, 161, 21))
        self.nama_label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.nama_label.setObjectName("nama_label")
        self.npm_label = QtWidgets.QLabel(self.centralwidget)
        self.npm_label.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.npm_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.npm_label.setObjectName("npm_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 70, 641, 451))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: #73B6BC;\n"
"color: black;\n"
"}")
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 161, 231))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    border: 2px solid #EDEEE9;\n"
"    background: #012A3B;\n"
"color: white;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.label.setObjectName("label")
        self.W_norm = QtWidgets.QRadioButton(self.groupBox)
        self.W_norm.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.W_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.W_norm.setObjectName("W_norm")
        self.lnW_norm = QtWidgets.QRadioButton(self.groupBox)
        self.lnW_norm.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.lnW_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.lnW_norm.setObjectName("lnW_norm")
        self.logW_norm = QtWidgets.QRadioButton(self.groupBox)
        self.logW_norm.setGeometry(QtCore.QRect(10, 80, 91, 16))
        self.logW_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.logW_norm.setObjectName("logW_norm")
        self.seperW_norm = QtWidgets.QRadioButton(self.groupBox)
        self.seperW_norm.setGeometry(QtCore.QRect(10, 100, 62, 14))
        self.seperW_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.seperW_norm.setObjectName("seperW_norm")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_4.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.label_4.setObjectName("label_4")
        self.Y_norm = QtWidgets.QRadioButton(self.groupBox)
        self.Y_norm.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.Y_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.Y_norm.setObjectName("Y_norm")
        self.lnY_norm = QtWidgets.QRadioButton(self.groupBox)
        self.lnY_norm.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.lnY_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.lnY_norm.setObjectName("lnY_norm")
        self.logY_norm = QtWidgets.QRadioButton(self.groupBox)
        self.logY_norm.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.logY_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.logY_norm.setObjectName("logY_norm")
        self.seperY_norm = QtWidgets.QRadioButton(self.groupBox)
        self.seperY_norm.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.seperY_norm.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.seperY_norm.setObjectName("seperY_norm")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(180, 0, 121, 16))
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setObjectName("label_5")
        self.nilai_W = QtWidgets.QTextEdit(self.widget)
        self.nilai_W.setGeometry(QtCore.QRect(180, 20, 104, 211))
        self.nilai_W.setStyleSheet("QTextEdit{\n"
"background:white;\n"
"color:black;\n"
"}")
        self.nilai_W.setObjectName("nilai_W")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(300, 0, 121, 16))
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setObjectName("label_6")
        self.nilai_Y = QtWidgets.QTextEdit(self.widget)
        self.nilai_Y.setGeometry(QtCore.QRect(300, 20, 104, 211))
        self.nilai_Y.setStyleSheet("QTextEdit{\n"
"color: black;\n"
"background: white;\n"
"}")
        self.nilai_Y.setObjectName("nilai_Y")
        self.plotGraph = QtWidgets.QPushButton(self.widget)
        self.plotGraph.setGeometry(QtCore.QRect(180, 240, 71, 21))
        self.plotGraph.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}")
        self.plotGraph.setObjectName("plotGraph")
        self.persamaan = QtWidgets.QLabel(self.widget)
        self.persamaan.setGeometry(QtCore.QRect(0, 290, 161, 61))
        self.persamaan.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font-size: 14px;\n"
"font-weight: bold;\n"
"}")
        self.persamaan.setAlignment(QtCore.Qt.AlignCenter)
        self.persamaan.setObjectName("persamaan")
        self.mse = QtWidgets.QLabel(self.widget)
        self.mse.setGeometry(QtCore.QRect(160, 290, 241, 61))
        self.mse.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font-size: 14px;\n"
"font-weight: bold;\n"
"}")
        self.mse.setAlignment(QtCore.Qt.AlignCenter)
        self.mse.setObjectName("mse")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 0, 211, 141))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    border: 2px solid #EDEEE9;\n"
"    background: #012A3B;\n"
"color: white;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.label_3.setStyleSheet("background: transparent;\n"
"color: white;")
        self.label_3.setObjectName("label_3")
        self.prediksi = QtWidgets.QTextEdit(self.groupBox_2)
        self.prediksi.setGeometry(QtCore.QRect(10, 60, 191, 31))
        self.prediksi.setStyleSheet("background: white;\n"
"color: black;")
        self.prediksi.setObjectName("prediksi")
        self.predict_button = QtWidgets.QPushButton(self.groupBox_2)
        self.predict_button.setGeometry(QtCore.QRect(70, 110, 71, 21))
        self.predict_button.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}")
        self.predict_button.setObjectName("predict_button")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 160, 211, 71))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    border: 2px solid #EDEEE9;\n"
"    background: rgb(238, 65, 76);\n"
"    color: white;\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.hasil_predik = QtWidgets.QLabel(self.groupBox_3)
        self.hasil_predik.setGeometry(QtCore.QRect(20, 10, 171, 51))
        self.hasil_predik.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font-weight: bold;\n"
"font-size: 15px;")
        self.hasil_predik.setText("")
        self.hasil_predik.setObjectName("hasil_predik")
        self.korelasi = QtWidgets.QLabel(self.widget)
        self.korelasi.setGeometry(QtCore.QRect(390, 290, 241, 61))
        self.korelasi.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    font-size: 14px;\n"
"font-weight: bold;\n"
"}")
        self.korelasi.setAlignment(QtCore.Qt.AlignCenter)
        self.korelasi.setObjectName("korelasi")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 30, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    text-align: center;\n"
"    color: white;\n"
"    font-size: bold;\n"
"    width: 100%;\n"
"background:transparent;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        Modul_modulpage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Modul_modulpage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 18))
        self.menubar.setObjectName("menubar")
        Modul_modulpage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Modul_modulpage)
        self.statusbar.setObjectName("statusbar")
        Modul_modulpage.setStatusBar(self.statusbar)

        self.retranslateUi(Modul_modulpage)
        QtCore.QMetaObject.connectSlotsByName(Modul_modulpage)

    def retranslateUi(self, Modul_modulpage):
        _translate = QtCore.QCoreApplication.translate
        Modul_modulpage.setWindowTitle(_translate("Modul_modulpage", "MainWindow"))
        self.back_button.setText(_translate("Modul_modulpage", "Menu Awal"))
        self.nama_label.setText(_translate("Modul_modulpage", "Nama"))
        self.npm_label.setText(_translate("Modul_modulpage", "NPM"))
        self.groupBox.setTitle(_translate("Modul_modulpage", "W dan Y"))
        self.label.setText(_translate("Modul_modulpage", "Bentuk W"))
        self.W_norm.setText(_translate("Modul_modulpage", "W"))
        self.lnW_norm.setText(_translate("Modul_modulpage", "ln W"))
        self.logW_norm.setText(_translate("Modul_modulpage", "log W"))
        self.seperW_norm.setText(_translate("Modul_modulpage", "1/W"))
        self.label_4.setText(_translate("Modul_modulpage", "Bentuk Y"))
        self.Y_norm.setText(_translate("Modul_modulpage", "Y"))
        self.lnY_norm.setText(_translate("Modul_modulpage", "ln Y"))
        self.logY_norm.setText(_translate("Modul_modulpage", "log Y"))
        self.seperY_norm.setText(_translate("Modul_modulpage", "1/Y"))
        self.label_5.setText(_translate("Modul_modulpage", "NILAI W"))
        self.label_6.setText(_translate("Modul_modulpage", "NILAI Y"))
        self.plotGraph.setText(_translate("Modul_modulpage", "PLOT"))
        self.persamaan.setText(_translate("Modul_modulpage", "Y = MW + B"))
        self.mse.setText(_translate("Modul_modulpage", "MSE = 0"))
        self.groupBox_2.setTitle(_translate("Modul_modulpage", "PREDIKSI"))
        self.label_3.setText(_translate("Modul_modulpage", "MASUKKAN NILAI W"))
        self.predict_button.setText(_translate("Modul_modulpage", "PREDICT"))
        self.groupBox_3.setTitle(_translate("Modul_modulpage", "HASIL PREDIKSI"))
        self.korelasi.setText(_translate("Modul_modulpage", "R = 0"))
        self.label_7.setText(_translate("Modul_modulpage", "KALKULATOR REGRESI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Modul_modulpage = QtWidgets.QMainWindow()
    ui = Ui_Modul_modulpage()
    ui.setupUi(Modul_modulpage)
    Modul_modulpage.show()
    sys.exit(app.exec_())
